import type { Metadata } from "next";
import TerminalLayout from "./components/TerminalLayout.tsx/TerminalLayout";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="code-font">
                <TerminalLayout>{children}</TerminalLayout>
            </body>
        </html>
    );
}
